# Site settings
name: M Hasanuddin
title: M Hasanuddin | Head of IT & Software engineer
description: Front-end engineer focused on Vue.js, Flutter, and clean UI/UX. Passionate about building scalable web/mobile apps and exploring AI & ML.
url: https://bonedeath.github.io/
baseurl: ''
lang: en
timezone: Asia/Jakarta
email: mhasannudin300@gmail.com
cover: https://bonedeath.github.io/img/og.png
logo: https://bonedeath.github.io/img/emojis/technologist.png
resume: https://bonedeath.github.io/resume.pdf

social:
  - title: email
    url: mailto:mhasannudin300@gmail.com
  - title: github
    url: https://github.com/bonedeath
  - title: linkedin
    url: https://www.linkedin.com/in/m-hasanuddin-webdev/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

# Optional plugins (disable if not supported by GitHub Pages)
plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap